# fly.toml app configuration file generated for checkmoneyapp on 2026-03-12T20:50:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'checkmoneyapp'
primary_region = 'fra'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/data"